services:
  - type: web
    name: telegram-info-bot
    runtime: image
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION 
        value: 3.11.10
